#ifndef DISPLAY_SLIDESHOW_GLOBAL_H
#define DISPLAY_SLIDESHOW_GLOBAL_H
#include <QtCore/qglobal.h>
#if defined(DISPLAY_SLIDESHOW_LIBRARY)
#  define DISPLAY_SLIDESHOWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DISPLAY_SLIDESHOWSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif