#ifndef DISPLAY_PROJECTM_GLOBAL_H
#define DISPLAY_PROJECTM_GLOBAL_H
#include <QtCore/qglobal.h>
#if defined(PROJECTM_LIBRARY)
#  define DISPLAY_PROJECTMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DISPLAY_PROJECTMSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif