#ifndef GAMING_NATIVE_GLOBAL_H
#define GAMING_NATIVE_GLOBAL_H
#include <QtCore/qglobal.h>
#if defined(GAMING_NATIVE_LIBRARY)
#  define GAMING_NATIVESHARED_EXPORT Q_DECL_EXPORT
#else
#  define GAMING_NATIVESHARED_EXPORT Q_DECL_IMPORT
#endif
#endif